#!/bin/bash
#CherryBot local system search - develop by emmanuelbreyaue 
#Version 0.07 
#emmanuelbreyaue@gmail.com


type=$1
keyword=$2
path=$3


function check_dir()
{
if [ -f $path ];then
exit
fi
}

function ver()
{
echo "
Ux Local System Search - Develop by Pampa-Rider
Under GPL License
Version 0.07
http://github.com/pampa-rider/cherrybot
"
}


function define_path()
{
	if [[ -z $path ]];	
	then
	echo ""
	#echo ${PWD}
	else
	check_dir
	#echo $path
	fi
	#echo $type
	#echo $keyword
}


function option_type()
{
case $type in
(-f)
list=$(./get-list.sh $type $path)
make-search
;;

(-d)
list=$(./get-list.sh $type $path)
make-search
;;

(-fd)
list=$(./get-list.sh $type $path)
make-search
;;

(-fnf)
#list=$(./get-list.sh -f $path)
./search-doc.sh $path $keyword
;;

(-ver)
#logo
ver
;;

(-?)
info_help
;;


(*)
info_help
exit
;;

esac


#-f buscar archivos
#-d .. directorios1
#-fd .. archivos y directorios
#-fnf .. en el interior de todos los archivos que contenga el eqiipo.
 
}

function make-search()
{
for k in $list;do
./get-search.sh $keyword $k
done
} 

function info_help()
{
echo "
Sintaxys: -x keyword /folder/subfolder

-f search files
-d .. search directories 
-fd .. search files and dir 
-fnf .. search inside the files."
}

echo -e "\e[44m"$path"\e[49m"
option_type
define_path



